import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import predictionService from '../../services/predictionService';
import {
  CheckCircle2,
  AlertTriangle,
  FileText,
  Download,
  Printer,
  ArrowLeft,
  RotateCcw,
  Sparkles,
  ShieldAlert,
  Building2,
  Calendar,
  Clock,
  Activity,
  Check,
  Stethoscope,
  X
} from 'lucide-react';

function PredictionResult() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showFullReportModal, setShowFullReportModal] = useState(false);

  useEffect(() => {
    async function loadReport() {
      try {
        const data = await predictionService.getPredictionById(id);
        setReport(data);
      } catch (err) {
        console.error('Failed to load prediction result', err);
      } finally {
        setLoading(false);
      }
    }
    loadReport();
  }, [id]);

  const handlePrintDownload = () => {
    // Generate print view in a new window with full AI medical disclaimer
    const printWin = window.open('', '_blank');
    if (!printWin) {
      alert('Please allow popups to download/print report.');
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AURA Health Report - ${report?.id}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #1e293b; background: #ffffff; }
          .header { border-bottom: 2px solid #2563eb; padding-bottom: 15px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
          .logo { font-size: 24px; font-weight: 900; color: #2563eb; }
          .disclaimer { background: #fef3c7; border: 1px solid #f59e0b; padding: 12px; border-radius: 8px; font-size: 12px; color: #92400e; margin-bottom: 20px; }
          .card { border: 1px solid #e2e8f0; padding: 20px; border-radius: 12px; margin-bottom: 20px; background: #f8fafc; }
          .title { font-size: 20px; font-weight: 800; color: #0f172a; margin-bottom: 8px; }
          .badge { display: inline-block; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: bold; }
          .badge-low { background: #dbeafe; color: #1e40af; }
          .badge-moderate { background: #fef3c7; color: #92400e; }
          .badge-high { background: #fee2e2; color: #991b1b; }
          ul { padding-left: 20px; font-size: 13px; line-height: 1.6; }
          .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; pt: 15px; font-size: 11px; color: #64748b; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">AURA Medical Assistant</div>
          <div>Report ID: <strong>${report?.id}</strong> | Date: ${report?.date}</div>
        </div>

        <div class="disclaimer">
          <strong>CLINICAL AI DISCLAIMER:</strong> This report is generated by AURA AI-assisted prediction systems for informational triage purposes only. It is <strong>NOT a medical diagnosis</strong>. Please consult a licensed medical professional for clinical diagnosis and treatment.
        </div>

        <div class="card">
          <div style="margin-bottom: 10px;">
            <span class="badge ${report?.riskLevel === 'High Attention' ? 'badge-high' : report?.riskLevel === 'Moderate Attention' ? 'badge-moderate' : 'badge-low'}">
              ${report?.riskLevel} • ${report?.confidence}% Confidence
            </span>
          </div>
          <div class="title">${report?.predictedCondition}</div>
          <p style="font-size: 13px; color: #475569;">${report?.description}</p>
        </div>

        <div class="card">
          <h3>Symptoms Analyzed</h3>
          <ul>
            ${report?.symptoms?.map(s => `<li>${s}</li>`).join('')}
          </ul>
        </div>

        <div class="card">
          <h3>Recommended General Precautions</h3>
          <ul>
            ${report?.precautions?.map(p => `<li>${p}</li>`).join('')}
          </ul>
        </div>

        <div class="card">
          <h3>Next Recommended Actions</h3>
          <ul>
            ${report?.recommendedActions?.map(a => `<li>${a}</li>`).join('')}
          </ul>
        </div>

        <div class="footer">
          AURA – Advanced Unified Responsive Assistant for Medical Emergencies | Generated for ${report?.demographics?.sex || 'Patient'} (${report?.demographics?.ageRange || 'N/A'})
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
      </html>
    `;

    printWin.document.write(htmlContent);
    printWin.document.close();
  };

  if (loading) {
    return (
      <div className="py-24 text-center space-y-4">
        <div className="w-12 h-12 rounded-2xl bg-blue-600 text-white flex items-center justify-center mx-auto animate-bounce shadow-lg shadow-blue-600/30">
          <Sparkles size={24} />
        </div>
        <p className="text-sm font-bold text-slate-600">Retrieving prediction report...</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="py-16 text-center space-y-4 bg-white rounded-3xl p-8 border border-slate-200">
        <AlertTriangle size={36} className="text-amber-500 mx-auto" />
        <h2 className="text-xl font-bold text-slate-800">Report Not Found</h2>
        <p className="text-xs text-slate-500">The requested prediction report ID does not exist.</p>
        <Link
          to="/patient/dashboard"
          className="inline-flex items-center gap-2 bg-blue-600 text-white font-bold px-4 py-2 rounded-xl text-xs"
        >
          Return to Dashboard
        </Link>
      </div>
    );
  }

  const isHighRisk = report.riskLevel === 'High Attention';
  const isModRisk = report.riskLevel === 'Moderate Attention';

  return (
    <div className="space-y-8 pb-16">
      
      {/* HEADER BAR */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/patient/dashboard')}
            className="p-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 transition-colors cursor-pointer"
            title="Back to Dashboard"
          >
            <ArrowLeft size={18} />
          </button>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-black uppercase tracking-wider text-blue-700 bg-blue-50 border border-blue-200 px-2.5 py-0.5 rounded-full flex items-center gap-1">
                <CheckCircle2 size={13} className="text-blue-600" />
                Analysis Complete
              </span>
              <span className="text-xs font-mono text-slate-400">ID: {report.id}</span>
            </div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-900 mt-1">
              AURA Health Prediction Report
            </h1>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handlePrintDownload}
            className="inline-flex items-center gap-2 bg-white hover:bg-slate-50 text-slate-700 font-bold px-4 py-2.5 rounded-xl border border-slate-200 text-xs shadow-2xs transition-colors cursor-pointer"
          >
            <Printer size={15} />
            <span>Print / Save PDF</span>
          </button>

          <Link
            to="/predict"
            className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2.5 rounded-xl text-xs shadow-xs transition-colors cursor-pointer"
          >
            <RotateCcw size={15} />
            <span>New Prediction</span>
          </Link>
        </div>
      </div>

      {/* PRIMARY RESULT CARD */}
      <section className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/90 shadow-sm space-y-6 relative overflow-hidden">
        
        {/* Urgency Color Top Ribbon */}
        <div
          className={`absolute top-0 left-0 right-0 h-2 ${
            isHighRisk ? 'bg-red-600' : isModRisk ? 'bg-amber-500' : 'bg-blue-600'
          }`}
        />

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 pt-2">
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center gap-2.5">
              <span
                className={`text-xs font-extrabold px-3 py-1 rounded-full uppercase tracking-wider ${
                  isHighRisk
                    ? 'bg-red-100 text-red-700 border border-red-200'
                    : isModRisk
                    ? 'bg-amber-100 text-amber-800 border border-amber-200'
                    : 'bg-blue-100 text-blue-800 border border-blue-200'
                }`}
              >
                {report.riskLevel}
              </span>

              <span className="text-xs text-slate-500 font-medium flex items-center gap-1">
                <Calendar size={13} />
                <span>{report.date} at {report.time}</span>
              </span>
            </div>

            <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
              {report.predictedCondition}
            </h2>

            <p className="text-slate-600 text-sm leading-relaxed max-w-2xl font-medium">
              {report.description}
            </p>
          </div>

          {/* Confidence Meter Badge */}
          <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl text-center min-w-[180px] shrink-0 space-y-2">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider block">AI Match Score</span>
            <div className="text-4xl font-black text-blue-600 tracking-tight">
              {report.confidence}%
            </div>
            <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden">
              <div
                className="bg-blue-600 h-full rounded-full transition-all duration-500"
                style={{ width: `${report.confidence}%` }}
              />
            </div>
          </div>
        </div>

        {/* Clinical Disclaimer Ribbon */}
        <div className="bg-amber-50/80 border border-amber-200/90 p-4 rounded-2xl flex items-start gap-3 text-xs text-amber-900">
          <ShieldAlert size={20} className="text-amber-600 shrink-0 mt-0.5" />
          <div>
            <span className="font-extrabold uppercase tracking-wider block">AI Triage Notice</span>
            <p className="mt-0.5 leading-relaxed">
              This report is generated by AI algorithms analyzing reported symptom combinations. It is <strong>not a medical diagnosis</strong>. Always consult a qualified healthcare professional for medical evaluation.
            </p>
          </div>
        </div>

      </section>

      {/* TWO COLUMNS: SYMPTOMS & PRECAUTIONS vs RECOMMENDED ACTIONS */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* LEFT COLUMN (7 Cols) */}
        <div className="lg:col-span-7 space-y-6">
          
          {/* SYMPTOMS ANALYZED */}
          <section className="bg-white rounded-3xl p-6 sm:p-7 border border-slate-200/90 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="font-black text-slate-900 text-lg">Symptoms Analyzed</h3>
              <span className="text-xs font-bold text-blue-600 bg-blue-50 px-2.5 py-0.5 rounded-full">
                {report.symptoms?.length || 0} Symptoms
              </span>
            </div>

            <div className="flex flex-wrap gap-2">
              {report.symptoms?.map((sym, idx) => (
                <span
                  key={idx}
                  className="inline-flex items-center gap-1.5 bg-slate-100 text-slate-800 font-bold text-xs px-3 py-2 rounded-xl border border-slate-200/80"
                >
                  <Check size={14} className="text-blue-600" />
                  <span>{sym}</span>
                </span>
              ))}
            </div>
          </section>

          {/* CONDITION PRECAUTIONS */}
          <section className="bg-white rounded-3xl p-6 sm:p-7 border border-slate-200/90 shadow-sm space-y-4">
            <h3 className="font-black text-slate-900 text-lg pb-3 border-b border-slate-100">
              Recommended General Precautions
            </h3>

            <ul className="space-y-3">
              {report.precautions?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-3 text-xs sm:text-sm text-slate-700 font-medium">
                  <span className="w-5 h-5 rounded-full bg-blue-50 text-blue-600 font-bold flex items-center justify-center text-[11px] shrink-0 mt-0.5 border border-blue-200">
                    {idx + 1}
                  </span>
                  <span className="leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </section>

        </div>

        {/* RIGHT COLUMN (5 Cols): RECOMMENDED ACTIONS & EMERGENCY SHORTCUT */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* NEXT RECOMMENDED ACTIONS */}
          <section className="bg-white rounded-3xl p-6 sm:p-7 border border-slate-200/90 shadow-sm space-y-4">
            <h3 className="font-black text-slate-900 text-lg pb-3 border-b border-slate-100">
              Next Action Steps
            </h3>

            <div className="space-y-3">
              {report.recommendedActions?.map((act, idx) => (
                <div
                  key={idx}
                  className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl flex items-start gap-3"
                >
                  <div className="p-1.5 bg-blue-100 text-blue-600 rounded-lg shrink-0 mt-0.5">
                    <Stethoscope size={16} />
                  </div>
                  <p className="text-xs text-slate-800 font-bold leading-relaxed">{act}</p>
                </div>
              ))}
            </div>
          </section>

          {/* URGENT CARE SHORTCUT CARD */}
          <section className="bg-gradient-to-br from-slate-900 to-indigo-950 text-white rounded-3xl p-6 shadow-md space-y-4">
            <div className="space-y-2">
              <span className="text-[11px] font-black uppercase tracking-wider text-purple-400">
                Healthcare Finder
              </span>
              <h3 className="text-lg font-black text-white">Need a Doctor or Hospital?</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Discover nearby 24/7 emergency facilities, real-time bed counts, and travel directions.
              </p>
            </div>

            <div className="flex flex-col gap-2 pt-2">
              <Link
                to="/hospitals"
                className="w-full inline-flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-xl text-xs shadow-md transition-colors"
              >
                <Building2 size={16} />
                <span>Find Nearby Hospitals</span>
              </Link>

              {isHighRisk && (
                <Link
                  to="/emergency"
                  className="w-full inline-flex items-center justify-center gap-2 bg-red-600 hover:bg-red-700 text-white font-bold py-3 px-4 rounded-xl text-xs shadow-md transition-colors"
                >
                  <AlertTriangle size={16} />
                  <span>Trigger Emergency SOS</span>
                </Link>
              )}
            </div>
          </section>

        </div>

      </div>

    </div>
  );
}

export default PredictionResult;
